version: '3'

services:
  django_app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: [ "bash", "./scripts/startup.sh" ]
    volumes:
      - .:/service
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    env_file:
      - .env